name: "RPi OLED Monitor"
version: "0.0.3"
description: "Display system info on a connected i2c OLED display"
url: "https://github.com/jxctn0/homeassistant-rpi-oled"
homeassistant_api: true
slug: rpi_oled
full_access: true
startup: application
boot: auto
arch:
    - aarch64
devices:
    - /dev/i2c-0:rw
    - /dev/i2c-1:rw
    - /dev/i2c-2:rw
    - /dev/i2c-3:rw
    - /dev/i2c-4:rw
    - /dev/i2c-5:rw
    - /dev/i2c-6:rw
options:
    bus_number: 1
    i2c_address: "0x3C"
    sensor_cpu_temp: sensor.processor_temperature
    sensor_cpu_use: sensor.processor_use
    sensor_ram_use: sensor.memory_use
    sensor_ram_free: sensor.memory_free
    sensor_disk_use: sensor.disk_use_
    sensor_disk_free: sensor.disk_free_
    sensor_net_tx: sensor.network_throughput_out_eth0
    sensor_net_rx: sensor.network_throughput_in_eth0
schema:
    bus_number: int
    i2c_address: str
    sensor_cpu_temp: str
    sensor_cpu_use: str
    sensor_ram_use: str
    sensor_ram_free: str
    sensor_disk_use: str
    sensor_disk_free: str
    sensor_net_tx: str
    sensor_net_rx: str
