name: "RPi OLED Monitor"
version: "0.0.2"
description: "Display system info on a connected i2c OLED display"
url: "https://github.com/jxctn0/homeassistant-rpi-oled"
homeassistant_api: true
slug: rpi_oled
full_access: true
startup: application
boot: auto
arch:
    - aarch64
devices:
    - /dev/i2c-0:rw
    - /dev/i2c-1:rw
    - /dev/i2c-2:rw
    - /dev/i2c-3:rw
    - /dev/i2c-4:rw
    - /dev/i2c-5:rw
    - /dev/i2c-6:rw
options:
    i2c Bus: 1
    OLED Type: "ssd1306"
schema:
    i2c Bus: "int(0,6)"
    OLED Type: "list(ssd1306)"
